### ISSUE TITLE
Running the "make cert-manager-self-signed-issuer-create" in step 7 fails

### ISSUE THREAD

**Issue by dthurston** [freeipa/freeipa-operator#54]
Part of step 7 in the "Quick Start" says:
When the cert-manager operator is installed, run this:
make cert-manager-self-signed-issuer-create

[dthursto@fedora ~]$ make cert-manager-self-signed-issuer-create
make: *** No rule to make target 'cert-manager-self-signed-issuer-create'.  Stop.

Looking in mk/cert-manager.mk there is no .PHONY entry for "cert-manager-self-signed-issuer-create".  I'm wondering what I'm doing wrong or if there should be an entry for that?

**Comment by frasertweedale** [comment]
@avisiedo could you please take a look when you have some cycles?

**Comment by avisiedo** [comment]
@dthurston thanks for opening the issue.

You are right, it should be an entry in the `mk/cert-manager.mk` file. I am going to restore the rules, and I will update the `REAMDE.md` file as I have seen that I missed the creation of the **scc** resource when using `make deploy` which is required actually.

**Comment by avisiedo** [comment]
closing issues as the pr is merged.
